### ISSUE TITLE
Cannot run training on GPU: undefined symbol: cudaHostRegister

### ISSUE THREAD

**Issue by sidnarayanan** [facebookresearch/PyTorch-BigGraph#154]
## Steps to reproduce

  1. Install CUDA 10.2, PyTorch 1.6.0. Verify that CUDA is available to PyTorch.
  2. pip install PBG from source with PBG_INSTALL_CPP=1
  3. Run `torchbiggraph/examples/fb15k.py` with the provided GPU config 

## Observed Results
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/data/snarayanan/venvs/ge/lib/python3.7/site-packages/torchbiggraph-1.0.1.dev0-py3.7-linux-x86_64.egg/torchbiggraph/train_gpu.py", line 158, in run
    res = cudart.cudaHostRegister(cptr, csize, cflags)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /data/snarayanan/venvs/ge/bin/python3: undefined symbol: cudaHostRegister
```

## Relevant Code

Tracing the crash to `train_gpu.py` brings me to these lines:

  ```python
            # FIXME: broken by D20249187
            # cudart = torch.cuda.cudart()
            cudart = ctypes.cdll.LoadLibrary(None)
            res = cudart.cudaHostRegister(cptr, csize, cflags)
  ```

Changing it to this doesn't help:
```python
            # FIXME: broken by D20249187
            cudart = torch.cuda.cudart()
            # cudart = ctypes.cdll.LoadLibrary(None)
            res = cudart.cudaHostRegister(cptr, csize, cflags)
```
apparently the call signature has changed:
```
    res = cudart.cudaHostRegister(cptr, csize, cflags)
TypeError: cudaHostRegister(): incompatible function arguments. The following argument types are supported:
    1. (arg0: capsule, arg1: int, arg2: int) -> torch._C._cudart.cudaError
```

I have a couple CUDA versions available locally, so to ensure they weren't conflicting, I used a Docker image containing only 10.2. This dockerfile reproduces the above failure.

```docker
FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 

RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         ca-certificates \
         libjpeg-dev \
         software-properties-common \
         ssh \
         unzip \
         libpng-dev && \
     rm -rf /var/lib/apt/lists/*

ARG PYTHON_VERSION=python3.7

RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update -y && apt install -y ${PYTHON_VERSION} \
                                    ${PYTHON_VERSION}-dev \
                                    python3-pip \
                                    vim

RUN ln -sf /usr/bin/${PYTHON_VERSION} /usr/bin/python3
RUN ln -sf /usr/bin/${PYTHON_VERSION} /usr/bin/python
RUN ln -sf /usr/bin/pip3 /usr/bin/pip

RUN pip install torch==1.6.0

RUN mkdir -p /usr/src/
RUN git clone https://github.com/facebookresearch/PyTorch-BigGraph /usr/src/ptbg

WORKDIR /usr/src/ptbg 
RUN PBG_INSTALL_CPP=1 pip install . 

WORKDIR /usr/src/ptbg/torchbiggraph/examples
CMD python3 fb15k.py --config configs/fb15k_config_gpu.py
```

**Comment by lw** [comment]
I remember that a while ago PyTorch didn't support CUDA 10.2. I think that has changed with version 1.6 but, just in case, could you try to use CUDA 10.1 and see what happens?

Also, AFAIK PyTorch bundles its own version of CUDA, so installing it on the system (like you did by picking a Docker image containing it) isn't necessary. I'm wondering whether it may even be harmful in this case as it risks introducing conflicting versions of CUDA that may create ambiguous symbol lookups. So another thing to try could be to pick a "vanilla" Docker image.

In general I am not that familiar with Docker so there may be other aspects I am missing. In general we have seen that Docker can cause issues with PBG, especially around memory allocations (e.g., it puts extra limits on how much shared memory we can allocate). Not sure if this is what is going on here, but it would be better if you could run on bare metal.

**Comment by sidnarayanan** [comment]
Thanks for taking a look! I provided the Docker image as a standalone example - I originally observed this problem running on bare metal. 

I confirm that I still see the same issue on CUDA 10.1. For good measure, I tested both on bare metal and Docker, and even removed all other native CUDA versions on my machine so as to avoid conflicts. `nvcc --version` confirms that my runtime API is 10.1. 

Also, unless I'm misunderstanding something, I don't think PyTorch bundles CUDA. Switching the base image to ubuntu:18.04 and installing `torch==1.6.0+cu101` gives the following:
```python
>>> torch.version.cuda
'10.1'
>>> torch.cuda.is_available()
False
```

**Comment by lw** [comment]
Ok, I may have been wrong about PyTorch bundling CUDA. Let's go back to CUDA 10.2.

One theory I have now is that when PyTorch loads CUDA it doesn't put its symbols in the global namespace. That would be weird but possible. I'm not sure how to test it though. One possibility: could you try running with the env var `TORCH_USE_RTLD_GLOBAL=1`?

Another thing to try is whether we could manage to load CUDA on our own, without relying on PyTorch. For that, let's try a few things in a Python prompt without loading PyTorch:
```
>>> import ctypes
>>> import ctypes.util
>>> handle = ctypes.cdll.LoadLibrary(ctypes.util.find_library("cudart"))
>>> count = ctypes.c_int(0)
>>> handle.cudaGetDeviceCount(ctypes.byref(count))
0
>>> count
c_int(8)
```
Let me know if that works for you.

**Comment by sidnarayanan** [comment]
Aha! Having gone back to CUDA 10.2, `TORCH_USE_RTLD_GLOBAL=1` does the trick when running `torchbiggraph_example_fb15k`. `nvidia-smi` shows the GPU in use and the training proceeds. 

Are there any undesirable side-effects of keeping this flag on all the time?

If it helps in tracing what happened, I ran that Python snippet. It works for me identically, except `count=1` in my case, as expected for my single-GPU test machine.

**Comment by lw** [comment]
Glad to hear you got it to work!

> Are there any undesirable side-effects of keeping this flag on all the time?

If you're just using it for launching PBG then I think it should be fine. It may start creating problems when you load other third-party libraries into the same interpreter in which you've already loaded PyTorch.

However, I don't think that such a flag should be necessary in the first place. I'll open an issue on the PyTorch repo to check what's the intended behavior here.

Since you got that snippet to run, we could also use that approach in the PBG code. I think it would however mean that we re-load CUDA for a second time, which should not be necessary and thus I'd prefer to avoid it if possible...

**Comment by lw** [comment]
Could you check one more thing? Does the FB15k demo work on GPU if you use PyTorch 1.5 (without that extra env var)? It would be helpful to know if it's a regression introduced in PyTorch 1.6 or something that was there before but is somehow triggered by your system. Thanks!

**Comment by sidnarayanan** [comment]
Yup, it looks like 1.6 introduces the problem. I can run the example in PyTorch 1.5.1/CUDA 10.1 without the env var.

**Comment by lw** [comment]
Thanks for checking that! We're trying to investigate this in https://github.com/pytorch/pytorch/issues/43006, in case you want to follow.

**Comment by sidnarayanan** [comment]
Just subscribed to the issue, thanks for the pointer :). I'm happy to mark this issue as closed, but also happy to leave it open if you'd like to wait for an upstream fix. Thanks again for your help!

**Comment by HenryYihengXu** [comment]
Hello! I also encountered the same error. I tried setting `TORCH_USE_RTLD_GLOBAL=1`, and the error is gone. But it then gave me the following error:
```
Process GPU #0:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/torchbiggraph/train_gpu.py", line 159, in run
    torch.cuda.check_error(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 225, in check_error
    raise CudaError(res)
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 219, in __init__
    msg = _cudart.cudaGetErrorString(code).decode('utf-8')
TypeError: cudaGetErrorString(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch._C._cudart.cudaError) -> str
```
I'm also running in a docker container. Here is my dockerfile:
```
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
RUN apt update
RUN apt install -y g++ \
         make \
         cmake \
         wget \
         unzip \
         vim \
         git \
         python3-pip
RUN pip3 install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
RUN mkdir /experiments
```
Do you know why is it happening? I would appreciate it!

**Comment by lw** [comment]
We still haven't gotten to the bottom of why `TORCH_USE_RTLD_GLOBAL` is needed, but as for the other error about `cudaGetErrorString` that was due to a bug in PyTorch that has now been fixed (see https://github.com/pytorch/pytorch/pull/41330). If you use the nightly/master version that should work.

As for why you're getting that error, we would know more if `cudaGetErrorString` worked, but as a start I'm guessing it may have to do with Docker, as we've already had various reports of Docker limiting the amount of shared/pinned memory that an application could have, and PBG is making heavy use of that. There are options to raise or remove those limits in Docker which I don't remember off the top of my head, but I'd suggest to run PBG on bare metal if you can as you'll be getting a better experience.

**Comment by stillmatic** [comment]
My experience with the `cudaHostRegister` error is that there is insufficient GPU memory available for the partitioned edgelists, and that we must reduce size of each edgelist file, either by passing fewer edges overall or by increasing partitions. Increasing number of GPU's does not seem to help. Unsure about the exact mechanisms but increasing partition count resolved the issues for me.

FWIW I used the nightly PyTorch build and still got the error, only increasing the number of partitions worked.

**Comment by adamlerer** [comment]
You could also try increasing numEdgeChunks if edge memory is the issue.

**Comment by lw** [comment]
Thanks for letting us know that the `cudaHostRegister` issue is related to a memory limitation. However, I don't think it's the GPU memory that's causing this, as `cudaHostRegister` only operates on host memory. It could be that your system is imposing limits on page-locked memory and/or on shared memory. This could be especially true if you're using Docker.

**Comment by stillmatic** [comment]
Yes, definitely could be a different root cause, and I am running on Docker, which could raise these kinds of edge cases.

Thanks for the pointers on memory limits - I had increased shared memory but not page-locked. Looking into that further, the NCCL docs ( https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html ) suggest increasing shared memory as well as adding the ` –ulimit memlock=-1` flag to unlimit pinned memory resources— I will try again with this flag.

**Comment by malteos** [comment]
I had the same issue - however without using Docker. Anyhow, setting `TORCH_USE_RTLD_GLOBAL=1` solved the issue for me as well (CUDA v10.2).
